apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-pizza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-pizza-app
  template:
    metadata:
      labels:
        app: django-pizza-app
    spec:
      containers:
        - name: django-pizza-app
          image: alejandroariaszuluaga/django-pizza-app:latest # Use DockerHub
          # image: localhost:5000/django-pizza-app:latest # Minikube local registry
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
