apiVersion: v1
kind: Service
metadata:
  name: django-pizza-app-service
spec:
  type: NodePort
  selector:
    app: django-pizza-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
